name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-quality-enforcer:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: commit back changed code
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Code quality enforced [Enforcer Bot]"
